# -*- coding: utf-8 -*-
"""Copy of Assignment - Integers, Floats & Booleans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lrSRwjPC8kck8jRtsGmh0lzhbJAQl-FQ

## <u>While doing this assignment only use those concepts which have been taught till now</u>

## <u>Problem 1</u>

In a cricket tournament, based on the outcome of a particular match a team gets following points:
* <code>wins</code> gets <code>3</code> points
* <code>draws</code> gets <code>1</code> points
* <code>losses</code> gets <code>0</code> points

Team Aravali plays <code>8</code> matches in this tournament. It wins <code>4</code> matches, loses <code>3</code> matches and draws <code>1</code>. What is the total number of points gained by the Team Aravali?
"""

# The outcome variables are defined below
wins = 4
losses = 3
draws = 1

# Calculate the total points gained by Team Aravali
aravali_points = wins*3+losses*0+draws*1

# Print the variable aravali_points
print(aravali_points)

"""## <u>Problem 2 </u>

* Root of a function $f(x)$ is defined as the value $x$ where $f(x)=0$
* Consider a quadratic function $ f(x) = x^2 + 3x - 4$

### Find the value of the function $f(x)$ at points   $x=2,x=-1, x=1$.
"""

# Calculate the value of the function f(x) at x = 2
func_evaluated_at_2 = 2**2+3*2-4

# Print the value below
func_evaluated_at_2

# Calculate the value of the function f(x) at x = -1
func_evaluated_at_minus1 = (-1)**2+3*(-1)-4

# Print the value below
func_evaluated_at_minus1

# Calculate the value of the function f(x) at x = 1
func_evaluated_at_1 = 1**2+3*1-4

# Print the type of the variable below
func_evaluated_at_1

"""### Return the boolean for each value of $x$ to find out whether that value is a root of $f(x)$"""

# Check whether 2 is a root of f(x)
func_evaluated_at_2 == 0        # This is not root

# Check whether -1 is a root of f(x)
func_evaluated_at_minus1==0    # This is not root

# Check whether 1 is a root of f(x)
func_evaluated_at_1   # This is root

"""## <u> Problem 3 </u>

A bag contains <code>45</code> apples, <code>65</code> oranges and <code>30</code> bananas. Find the percentage of each type of food items in the bag.
"""

# Calculate the percentage of apples and print the variable
apple_percentage=45/(45+65+30)*100
print(apple_percentage)

# Calculate the percentage of oranges and print the variable
orange_percentage=65/(45+65+30)*100
print(orange_percentage)

# Calculate the percentage of bananas and print the variable

banana_percentage=30/(45+65+30)*100
print(banana_percentage)

"""## <u>Problem 4</u>

You were playing a fun guessing game during your school break. There were a total of 100 participants excluding you. Out of these 100 people, 30 were Maths Majors, 45 were Economics Majors and 25 were Physics Majors.

The game was divided into three rounds.

* In the first round, you had to guess the number of Maths Majors and you <b>correctly</b> guessed 20 of them.
* In the second round, you had to guess the number of Economics Majors and you <b>correctly</b> guessed 30 of them.
* In the final third round, you had to guess the number of Physics Majors and you <b>correctly</b> guessed 20 of them.

### Accuracy is defined as the number of correct guesses upon total number of people in the group (expressed in percentage)

* ### Define your variables
"""

# Store the number of Maths majors
Maths_majors=30

# Store the number of Economics majors
Economics_majors=45

# Store the number of Physics majors
Physics_majors=25

# Store the number of your correct guesses of Maths majors
Maths_majors_cguess=20

# Store the number of your correct guesses of Economics majors
Economics_majors_cguess=30

# Store the number of your correct guesses of Physics majors
Physics_majors_cguess=20

"""* ### Calculate your accuracy in each of the three rounds"""

# Print the Maths accuracy
a=Maths_majors_cguess/Maths_majors*100
print(a)

# Print the Economics accuracy
b=Economics_majors_cguess/Economics_majors*100
print(b)

# Print the Physics accuracy
c=Physics_majors_cguess/Physics_majors*100
print(c)

"""* ### Calculate your overall accuracy in the entire game"""

# Print the overall accuracy
(a+b+c)/3

