# -*- coding: utf-8 -*-
"""Copy of Assignment - Functions & Methods.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E7R3qGMTTZIq4quSWII7ZYLmShJJKUd2

# <u> Problem 1</u>

### Write a function which takes the excel column name as an input and returns the corresponding column number. A few examples are :

* column name = <code>'J'</code> , column number = <code>10</code>
* column name = <code>'AP'</code> , column number = <code>42</code>
* column name = <code>'AAA'</code>, column number = <code>703</code>
"""

def get_excel_column_number(column_name):
  '''
  This functions returns the corresponding column number for an excel column name
  '''
  # Write your code here
  dict={'A':1,'B':2,'C':3,'D':4,'E':5,'F':6,'G':7,'H':8,'I':9,'J':10,'K':11,'L':12,'M':13,'N':14,'O':15,'P':16,'Q':17,'R':18,'S':19,'T':20,'U':21,'V':22,'W':23,'X':24,'Y':25,'Z':26}
  num =0
  lenalpha=len(column_name)
  for i in range(lenalpha):
    power=lenalpha-i-1
    num = dict[column_name[i]]*(26**power)+num
  return num;

# Check
get_excel_column_number('BD')

# Check
get_excel_column_number('ALQ')

get_excel_column_number('J')

get_excel_column_number('AP')

get_excel_column_number('AAA')

"""# <u> Problem 2</u>

### We evaluate a standard machine learning classification model using various evaluation metrics. A classification model is a model which classifies a given observation or an event to a fixed set of categories. Suppose I train a machine learning model to classify images of cats and dogs. For each image, the machine classifies the image with either a <code>'Cat'</code> or a <code>'Dog'</code>. So in essence for each input image, there is a corresponding output by the model. This output can either be a <code>'Cat'</code> or a <code>'Dog'</code>.

### To evaluate such a machine learning model which is trained to classify a given observation with at most two labels, a lot of candidate evaluation metrics are available. Accuracy is one of such evaluation metrics.

### <u> Accuracy defintion </u> : Suppose you are given 20 input images of cats and dogs. You already know from these images that there are 11 cats and 9 dogs. You train a machine learning model to classify these images into cats and dogs. The machine predicts 9 cats correctly and 8 dogs correctly. The accuracy of the model is then defined as (correctly predicted cats and dogs)/(total cats and dogs). In this case it is (9+8)/(11+9) = 17/20 = 0.85 or 85%. It is a good practice to report the accuracy in percentages

### You are given two lists each of length 20 : one list contains the actual labels for the images of cats and dogs. The other list contains the predicted labels (by the machine) for the images of cats and dogs.

### How to read the two lists ? For example for the first image, actual label is Cat and the predicted label is Cat. For the last image, actual label is Dog and the predicted label is Cat. The same index in the two lists corresponds to the same image
"""

actual_labels = ['Cat','Dog','Cat','Cat','Dog','Cat','Dog','Cat','Cat','Cat','Dog','Dog','Cat','Cat','Cat','Dog','Dog','Dog','Cat','Dog']

predicted_labels = ['Cat','Dog','Cat','Cat','Dog','Cat','Dog','Cat','Dog','Dog','Dog','Dog','Cat','Cat','Cat','Dog','Dog','Dog','Cat','Cat']

"""### Write a function to calculate the accuracy. This functions takes two lists as inputs and returns the accuracy score in percentage"""

def calculate_accuracy(actual, predicted):
  '''
  This functions calculates the accuracy based on two input lists
  '''
  # Write your code here
  count=0
  for pet in range(len(actual)):
      if actual[pet]==predicted[pet]:
        count=count+1
  accuracy=count/len(actual)
  return accuracy

# Print the accuracy score for the given lists
print(calculate_accuracy(actual_labels,predicted_labels))

"""* ### <b><u>Precision</u></b> for cats is defined as the number of correctly predicted cats divided by the number of predicted cats. Report precision in percentages.

* ### <b><u>Recall</u></b> for cats is defined as the number of correctly predicted cats divided by the actual number of cats. Report recall in percentages.

### We can define the same two metrics for dogs as well.

# <u> Problem 3 </u>

### Write a Python function which returns the precision and recall for a given input label. Use the same two lists
"""

def precision_recall(label = 'Dog'):
  '''
  This functions returns a tuple of precision and recall for a given input label
  '''
  # Your code here
  count=0
  predicted_dogs=predicted_labels.count('Dog')
  for i in range(len(actual_labels)):
    if actual_labels[i]==predicted_labels[i]:
      if actual_labels[i]==label:
        count=count+1
  precision=count/predicted_dogs
  return precision

precision_recall()

"""# <u> Problem 4 </u>

### Write a Python function which takes a sentence and a length value as inputs and returns the counts of those words from the sentence whose length is equal to the provided input length value.

### Suppose if the input for the length value is 5, it will return the count of all those words which are of length 5
"""

marvel_quote = "The world has changed and none of us can go back. All we can do is our best, and sometimes the best that we can do is to start over."

# Your function below. Make sure to remove the special characters such as full stop and comma.
def fixed_length_word_counts(sentence, length=3):
  '''
  This function returns the count of the words with the given input length
  '''
  # Your code below
  count=0
  sntence_list=sentence.split(" ")
  for i in range(len(sntence_list)):
    if len(sntence_list[i])==length:
      count=count+1
  return count

# Check on the sample sentence
fixed_length_word_counts(marvel_quote)

