# -*- coding: utf-8 -*-
"""Assignment Solution - Functions and Methods.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IBtDSTNBacMknLw706V8HMG7KKVkxIg4

# <u> Problem 1</u>

### Write a function which takes the excel column name as an input and returns the corresponding column number. A few examples are :

* column name = <code>'J'</code> , column number = <code>10</code>
* column name = <code>'AP'</code> , column number = <code>42</code>
* column name = <code>'AAA'</code>, column number = <code>703</code>
"""

def get_excel_column_number(column_name):
  '''
  This functions returns the corresponding column number for an excel column name
  '''
  # Step 1 : Get the dictionary mapping

  list_of_nums = list(range(1,27,1))
  alphabets = 'abcdefghijklmnopqrstuvwxyz'
  alphabet_list = [char.upper() for char in alphabets]

  # Zip them together
  alphabet_num_dict = dict(zip(alphabet_list,list_of_nums))

  # Step 2 : Starting from the righmost character of the column name, keep adding the column number
  multiplier = 1
  colNum = 0
  for letter in column_name[::-1]:
    print(letter)
    print(alphabet_num_dict[letter])
    colNum = colNum + alphabet_num_dict[letter]* multiplier
    print(colNum)
    multiplier = multiplier * 26
    print(multiplier)
  return colNum

# Check
get_excel_column_number('BD')

# Check
get_excel_column_number('ZZ')

"""# <u> Problem 2</u>

### We evaluate a standard machine learning classification model using various evaluation metrics. A classification model is a model which classifies a given observation or an event to a fixed set of categories. Suppose I train a machine learning model to classify images of cats and dogs. For each image, the machine classifies the image with either a <code>'Cat'</code> or a <code>'Dog'</code>. So in essence for each input image, there is a corresponding output by the model. This output can either be a <code>'Cat'</code> or a <code>'Dog'</code>.

### To evaluate such a machine learning model which is trained to classify a given observation with at most two labels, a lot of candidate evaluation metrics are available. Accuracy is one of such evaluation metrics.

### <u> Accuracy defintion </u> : Suppose you are given 20 input images of cats and dogs. You already know from these images that there are 11 cats and 9 dogs. You train a machine learning model to classify these images into cats and dogs. The machine predicts 9 cats correctly and 8 dogs correctly. The accuracy of the model is then defined as (correctly predicted cats and dogs)/(total cats and dogs). In this case it is (9+8)/(11+9) = 17/20 = 0.85 or 85%. It is a good practice to report the accuracy in percentages

### You are given two lists each of length 20 : one list contains the actual labels for the images of cats and dogs. The other list contains the predicted labels (by the machine) for the images of cats and dogs.

### How to read the two lists ? For example for the first image, actual label is Cat and the predicted label is Cat. For the last image, actual label is Dog and the predicted label is Cat. The same index in the two lists corresponds to the same image
"""

actual_labels = ['Cat','Dog','Cat','Cat','Dog','Cat','Dog','Cat','Cat','Cat','Dog','Dog','Cat','Cat','Cat','Dog','Dog','Dog','Cat','Dog']

predicted_labels = ['Cat','Dog','Cat','Cat','Dog','Cat','Dog','Cat','Dog','Dog','Dog','Dog','Cat','Cat','Cat','Dog','Dog','Dog','Cat','Cat']

"""### Write a function to calculate the accuracy. This functions takes two lists as inputs and returns the accuracy score in percentage"""

def calculate_accuracy(actual, predicted):
  '''
  This function calculates the accuracy based on two input lists
  '''
  # Write your code here
  zipped_list = zip(actual,predicted)

  correct_predictions = sum([1 for act,pred in zipped_list if act==pred])
  total_images = len(actual)

  accuracy = round(correct_predictions * 100/total_images,2)


  return accuracy

# Print the accuracy score for the given lists
calculate_accuracy(actual_labels,predicted_labels)

"""* ### <b><u>Precision</u></b> for cats is defined as the number of correctly predicted cats divided by the number of predicted cats. Report precision in percentages.

* ### <b><u>Recall</u></b> for cats is defined as the number of correctly predicted cats divided by the actual number of cats. Report recall in percentages.

### We can define the same two metrics for dogs as well.

# <u> Problem 3 </u>

### Write a Python function which returns the precision and recall for a given input label. Use the same two lists
"""

def precision_recall(label = 'Dog'):
  '''
  This function returns a tuple of precision and recall for a given input label
  '''
  # Your code here
  num_pred_labels = predicted_labels.count(label)
  num_actual_labels = actual_labels.count(label)

  # Write your code here
  zipped_list = zip(actual_labels,predicted_labels)

  # Calculate number of correctly predicted labels
  correct_predictions = 0
  for act,pred in zipped_list:
    if (act == label) & (pred == label):
      correct_predictions+=1

  # Calculate precision
  precision = correct_predictions*100/num_pred_labels

  # Calculate recall
  recall = correct_predictions*100/num_actual_labels

  return precision,recall

precision_recall(label='Dog')

"""# <u> Problem 4 </u>

### Write a Python function which takes a sentence and a length value as inputs and returns the counts of those words from the sentence whose length is equal to the provided input length value.

### Suppose if the input for the length value is 5, it will return the count of all those words which are of length 5
"""

marvel_quote = "The world has changed and none of us can go back. All we can do is our best, and sometimes the best that we can do is to start over."

# Your function below. Make sure to remove the special characters such as full stop and comma.
def fixed_length_word_counts(sentence, length=3):
  '''
  This function returns the count of the words with the given input length
  '''
  # Your code below
  sentence = sentence.replace(',','').replace('.','')
  list_of_words = sentence.split(' ')

  length_words = [word for word in list_of_words if len(word) == length]

  return len(length_words)

# Check on the sample sentence
fixed_length_word_counts(marvel_quote,length=4)