# -*- coding: utf-8 -*-
"""Copy of Assignment - Tuples, Sets and Dictionaries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Chs6ZgqlxNW_7s7rcI1xkB2OBgAhAT-E

## <u>While doing this assignment only use those concepts which have been taught till now</u>

## <u>Problem 1</u>

### Another measure of average

* Mode is defined as the value that appears most often in a set of data values. Mode corresponds to the most frequent value.
* You are given a list of numbers and you need to calculate the mode of this list
"""

# A list containing average daily temperature over 10 days
temperatures = [34, 40, 29, 33, 42, 40, 39, 34, 34,33 ]

# Step 1 : Find the unique set of values. Store this in a list
unique_temperatures = set(temperatures)

# Print the unique temperature list
unique_temperatures

# Step 2 : Create an empty dictionary which will contain the unique temperatures as keys and their counts in the original temperatures list as values
temp_dict = {}
# Set the values for each key separately
# First key
temp_dict[29]=temperatures.count(29)


# Second key

temp_dict[33]=temperatures.count(33)

# Third key

temp_dict[34]=temperatures.count(34)

# Fourth key

temp_dict[39]=temperatures.count(39)

# Fifth key

temp_dict[40]=temperatures.count(40)

# Sixth key
temp_dict[42]=temperatures.count(42)

print(temp_dict)

# Step 3: Store the dictionary values in a list

temp_dict_frequencies=list(temp_dict.values())
# Print the list of dictionary values
print(temp_dict_frequencies)

# Find the index of the most frequent temperature value
most_frequent_temp_index=temp_dict_frequencies.index(max(temp_dict_frequencies))

# most_frequent_temp_index =

# Print the index
print(most_frequent_temp_index)

# Step 4 : Create the list of dictionary keys
temp_dict_keys = list(temp_dict.keys())

# Print the list of dictionary keys
print(temp_dict_keys)
# Calculate the mode temperature
mode_temp =(max(temp_dict_frequencies))
print(mode_temp)

"""## <u>Problem 2 </u>

### Challenging the immutability of tuples

You are given a list of tuples. You need to replace the last element of the last tuple
"""

# Input list of tuples

list_of_tuples = [(10,20,30),(30,40,50),(50,60,70)]


# Expected output : Replace the last element 70 with 100
# output_list = [(10,20,30),(30,40,50),(50,60,100)]

# Your code here
list_of_tuples[-1]=(50,60,100)
# Print the output list
print(list_of_tuples)

"""## <u> Problem 3 </u>

Natural Language Processing or NLP is one of the most promising fields in Machine Learning. Most of the times in NLP we deal with the textual data (a bunch of strings). Sometimes when we are processing the text, it is a common practice to get rid of some set of stop words from our original text. By default stop words are very common words used in English language such as and, or, punctuations etc.

In this exercise, you are provided with a default set of stop words and you need to add some extra set of custom words.
"""

# A sample sentence

sentence = 'Hello, good morning folks! Today we will announce the half yearly performance results of the company. Due to the ongoing COVID-19 pandemic, our profits have declined by 60% as compared to the last half yearly results'

# Print your sentence
print(sentence)

# Default set of stop words
stop_words = {"i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself",
              "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself",
              "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that",
              "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had",
              "having", "do", "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because",
              "as", "until", "while", "of", "at", "by"s, "for", "with", "about", "against", "between", "into",
              "through", "during", "before", "after", "above", "below", "to", "from", "up", "down", "in", "out",
              "on", "off", "over", "under", "again", "further", "then", "once", "here", "there", "when", "where",
              "why", "how", "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "no",
              "nor", "not", "only", "own", "same", "so", "than", "too", "very", "s", "t", "can", "will", "just",
              "don", "should", "now"}

stop_words_list=list(stop_words)
len(stop_words_list)

# Update the set of stop words by adding the custom stop words
custom_stop_words = ["hello","good","morning","half","yearly"]

# Your code here
updated_stop_words=stop_words_list+custom_stop_words

# Print the updated stop words
print(updated_stop_words)
len(updated_stop_words)

# Do the same task another way. Keep in mind to use the original set of stop_words for this piece of code
custom_stop_words=set(custom_stop_words)
stop_words=stop_words.union(custom_stop_words)
# Print the updated stop words
print(stop_words)
len(stop_words)

"""## <u>Problem 4</u>

 Write a Python script to check whether a given key already exists in a dictionary. If it does, drop that key from the dictionary. If it does not, add that key and corresponding value to the dictionary
"""

# Your dictionary
employee_dict = {'Name':'Sanket','Skills':['Python','Machine Learning','Deep Learning'],'Band':6.0,
                 'Promotion Year':[2016,2018,2020]}

# Check if the key 'Employee_ID' is present in the dictionary. Hint : use a boolean variable to store this value
if employee_dict.get("Employee_ID") is not None:
  employee_dict.pop("Employee_ID")
else:
  employee_dict["Employee_ID"]=4503233

# If not present add this key to this dictionary and the corresponding value to be 4503233

# Check if the key 'Band' is present in the dictionary.
if employee_dict.get("Band") is not None:
  employee_dict.pop("Band")

# If present, drop this key from the dictionary

# Print the updated dictionary
employee_dict

