# -*- coding: utf-8 -*-
"""Assignment Solution - Statements, Indentation and Conditionals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jz4B-ixWorP_B8ywQ0HSnI9hE6yFe-n4

## <u>While doing this assignment only use those concepts which have been taught till now</u>

## <u>Problem 1</u>

### As an analyst, you had to present the quarterly performance results of your client. The data which you were provided was on daily basis. To complete this task, you needed to extract the quarter from a given date. For example:

* if the date lies between 1st Jan, 2020 - 31st March, 2020, you need to extract the corresponding quarter as '2020-Q1'

* if the date lies between 1st April, 2020 - 30th June, 2020, the extracted quarter will be '2020-Q2'

* if the date lies between 1st July, 2020 - 30th September, 2020, the extracted quarter will be '2020-Q3'

* if the date lies between 1st October, 2020 - 31st Decemeber, 2020 then the extracted quarter will be '2020-Q4'
"""

# Take a proper date input from the user in the format YYYY-MM-DD. Consider this date as a string
user_date = input()

# Write your code using if else statements to extract the quarter
date_year = user_date[:4]
date_month = user_date[5:7]

# Store the quarter value in a string variable named quarter

if (date_month >= '01') & (date_month <='03'):
    quarter = date_year + '-Q1'
elif (date_month >= '04') & (date_month <='06'):
    quarter = date_year + '-Q2'
elif (date_month >= '07') & (date_month <='09'):
    quarter = date_year + '-Q3'
else:
    quarter = date_year + '-Q4'

# Print the extracted quarter
print(quarter)

"""## <u>Problem 2 </u>

* You went out in your local neighbourhood to collect the data of people residing in the locale. You surveyed 5 people and collected some data and stored that in a dictionary. You recorded their names, their age, their sex, their heights(in cms) and their weights(in kgs)
"""

# Surveyed data

locality_data = {'Name' : ['Abhinav','Sohail','Dheeraj','Rashmi','Vaishali'],
                  'Age' : [42,29,35,28,32],
                  'Sex' : ['Male', 'Male','Male','Female','Female'] ,
                  'Height' : [172,175,170,168,170],
                  'Weight' : [70,82,60,55,64]
                 }

"""* Find the mean and median heights and weights of the people in your locality"""

# Calculate the mean height and print it
heights = locality_data['Height']
# Calculate the mean of the heights
mean_height = sum(heights)/len(heights)
print(mean_height)


# Calculate the median height and print it
sorted_heights = sorted(heights)
median_height = sorted_heights[int((len(sorted_heights)+1)/2) - 1]
print(median_height)



# Calculate the mean weight and print it
weights = locality_data['Weight']
# Calculate the mean of the weights
mean_weight = sum(weights)/len(weights)
print(mean_weight)


# Calculate the median height and print it
sorted_weights = sorted(weights)
median_weight = sorted_weights[int((len(sorted_weights)+1)/2 )- 1]
print(median_weight)

"""* Write a Python code to print the first three elements from the list of age values corresponding to the key 'Age'"""

# Python code to print the first three elements if the key is 'Age'

ages = locality_data['Age'][:3]
print(ages)

"""* Write a Python code to print the last two elements of the name list if the list of values corresponding to the key 'Name' contains the element 'Rashmi' else print 'Name not found'"""

# Your code below
name_list = locality_data['Name']

if 'Rashmi' in name_list:
  print(name_list[-2:])
else:
  print("Name not found")

"""## <u> Problem 3 </u>

A student will not be allowed to sit in exam if his/her attendence is less than 75%.

Take following input from user
* Number of classes held
* Number of classes attended.
"""

# Enter your input

print("Number of classes held")
classes_held = int(input())

print("Number of classes attended")
classes_attended = int(input())

# Calculate the attendance percentage
attendance = classes_attended*100/classes_held

"""And print the following statements based on the condition above

* percentage of class attended
* Is student is allowed to sit in exam or not.
"""

# Your code here
print(f'Percentage of class attended is {attendance}')

if attendance < 75:
  print("You are not allowed to sit in the exam")
else:
  print("You are allowed to sit in the exam")

"""## <u>Problem 4</u>

### A school has following rules for grading system:
* Below 25 - F
* 25 to 45 - E
* 45 to 50 - D
* 50 to 60 - C
* 60 to 80 - B
* Above 80 - A

Write a Python code which takes marks as inputs from the user and print the corresponding grade.
"""

# Your input here
print("Enter your marks")
marks = int(input())

# Your coder here to print the corresponding grade

if marks<25:
  print("F")
elif marks>=25 and marks<45:
  print("E")
elif marks>=45 and marks<50:
  print("D")
elif marks>=50 and marks<60:
  print("C")
elif marks>=60 and marks<80:
  print("B")
else:
  print("A")