# -*- coding: utf-8 -*-
"""Copy of Assignment - Statements, Indentation and Conditionals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hLBDbK9CRA-bKGiiGKRtizuMxLkQSf02

## <u>While doing this assignment only use those concepts which have been taught till now</u>

## <u>Problem 1</u>

### As an analyst, you had to present the quarterly performance results of your client. The data which you were provided was on daily basis. To complete this task, you needed to extract the quarter from a given date. For example:

* if the date lies between 1st Jan, 2020 - 31st March, 2020, you need to extract the corresponding quarter as '2020-Q1'

* if the date lies between 1st April, 2020 - 30th June, 2020, the extracted quarter will be '2020-Q2'

* if the date lies between 1st July, 2020 - 30th September, 2020, the extracted quarter will be '2020-Q3'

* if the date lies between 1st October, 2020 - 31st Decemeber, 2020 then the extracted quarter will be '2020-Q4'
"""

# Take a proper date input from the user in the format YYYY-MM-DD. Consider this date as a string
user_date = input()

# Write your code using if else statements to extract the quarter
date_year = int(user_date[9:])
date_month = user_date[4:7]
# Store the quarter value in a string variable named quarter
if(date_month=="Jan" or date_month=="Feb" or date_month=="March"):
  print(f'{date_year}-Q1')
  quarter='Q1'
elif(date_month=="April" or date_month=="May" or date_month=="June"):
  print(f'{date_year}-Q2')
  quarter='Q2'
elif(date_month=="July" or date_month=="August" or date_month=="September"):
  print(f'{date_year}-Q3')
  quarter='Q3'
elif(date_month=="October" or date_month=="November" or date_month=="December"):
  print(f'{date_year}-Q4')
  quarter='Q4'
else:
  print("Invalid month")

# Print the extracted quarter
print(quarter)

"""## <u>Problem 2 </u>

* You went out in your local neighbourhood to collect the data of people residing in the locale. You surveyed 5 people and collected some data and stored that in a dictionary. You recorded their names, their age, their sex, their heights(in cms) and their weights(in kgs)
"""

# Surveyed data

locality_data = {'Name' : ['Abhinav','Sohail','Dheeraj','Rashmi','Vaishali'],
                  'Age' : [42,29,35,28,32],
                  'Sex' : ['Male', 'Male','Male','Female','Female'] ,
                  'Height' : [172,175,170,168,170],
                  'Weight' : [70,82,60,55,64]
                 }

"""* Find the mean and median heights and weights of the people in your locality"""

# Calculate the mean height and print it
mean_height=sum(locality_data['Height'])/len(locality_data['Height'])
print(mean_height)
# Calculate the median height and print it
n=len(locality_data['Height'])
locality_data['Height'].sort()
if(len(locality_data['Height'])%2==0):
  print(locality_data['Height'])
  median_height=locality_data['Height'][n//2]
else:
  median_height=locality_data['Height'][((n+1)//2)]
print(median_height)
# Calculate the mean weight and print it
mean_weight=sum(locality_data['Weight'])/len(locality_data['Weight'])
print(mean_weight)

# Calculate the median weight and print it
n=len(locality_data['Weight'])
locality_data['Weight'].sort()
if(len(locality_data['Weight'])%2==0):
  print(locality_data['Weight'])
  median_weight=locality_data['Weight'][n//2]
else:
  median_weight=locality_data['Weight'][((n+1)//2)]

print(median_weight)

"""* Write a Python code to print the first three elements from the list of age values corresponding to the key 'Age'"""

# Python code to print the first three elements for the key 'Age'

ages = locality_data['Age'][0:3]
print(ages)

"""* Write a Python code to print the last two elements of the name list if the list of values corresponding to the key 'Name' contains the element 'Rashmi' else print 'Name not found'"""

# Your code below
i='Rashmi'
if(i in locality_data['Name']):
  print(locality_data['Name'][-1],locality_data['Name'][-2])
else:
  print('Name not found')

"""## <u> Problem 3 </u>

A student will not be allowed to sit in exam if his/her attendence is less than 75%.

Take following input from user
* Number of classes held
* Number of classes attended.
"""

# Enter your input

print("Number of classes held")
classes_held = int(input())

print("Number of classes attended")
classes_attended = int(input())

# Calculate the attendance percentage
attendance = classes_attended*100/classes_held

print(f'The attendance is {attendance}')

"""And print the following statements based on the condition above

* percentage of class attended
* Is student is allowed to sit in exam or not.
"""

# Your code here
print(attendance)
if(attendance>=75):
  print("Student is allowed")
else:
  print("Student is not allowed")

"""## <u>Problem 4</u>

### A school has following rules for grading system:
* Below 25 - F
* 25 to 45 - E
* 45 to 50 - D
* 50 to 60 - C
* 60 to 80 - B
* Above 80 - A

Keep the left number inclusive and the right number exclusive, something like [25,45) for grade E where the set is closed at 25 and open at 45.

Write a Python code which takes marks as inputs from the user and print the corresponding grade.
"""

# Your input here
print("Enter your marks")
marks = int(input())

# Your code here to print the corresponding grade
if(marks>=80):
  print('Grade: A')
elif(marks>=60 and marks<80):
  print('Grade B')
elif(marks>=50 and marks<60):
  print('Grade C')
elif(marks>=45 and marks<50):
  print('Grade D')
elif(marks>=25 and marks<45):
  print('Grade E')
elif(marks<25):
  print('Grade F')

