# -*- coding: utf-8 -*-
"""Competetive Coding I - Solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Rwj5YiS0qE_tksHeWtHyKs-wSyiI1Wp

# <u><b>Problem Statement

### A student is taking a cryptography class and has found anagrams to be very useful. Two strings are anagrams of each other if the first string's letters can be rearranged to form the second string. In other words, both strings must contain the same exact letters in the same exact frequency. For example, bacdc and dcbac are anagrams, but bacdc and dcbad are not.

### The student decides on an encryption scheme that involves two large strings. The encryption is dependent on the minimum number of character deletions required to make the two strings anagrams. You need to determine this number.

### Given two strings, $a$ and $b$, that may or may not be of the same length, determine the minimum number of character deletions required to make $a$ and $b$ anagrams. Any characters can be deleted from either of the strings. The strings $a$ and $b$ consist of lowercase English alphabets.

**Example**

<code>a = 'cde'</code>

<code>b = 'dcf' </code>

### Delete $e$ from $a$ and $f$ from $b$ so that the remaining strings are $cd$ and $dc$ which are anagrams. This takes 2 character deletions.

## **Function Description**

### Create a <code>makeAnagram</code> function below.

### **Inputs:**

### string a: a string

### string b: another string

### **Output:**

### int: the minimum total characters that must be deleted

# Solution
"""

def makeAnagram(a, b):
    str1 = a
    str2 = b

    CHARS = 26

    # make hash array for both string
    # and calculate
    # frequency of each character
    count1 = [0]*CHARS
    count2 = [0]*CHARS

    # count frequency of each character
    # in first string
    i = 0
    while i < len(str1):
        count1[ord(str1[i])-ord('a')] += 1
        i += 1

    # count frequency of each character
    # in second string
    i =0
    while i < len(str2):
        count2[ord(str2[i])-ord('a')] += 1
        i += 1

    # traverse count arrays to find
    # number of characters
    # to be removed
    result = 0
    for i in range(26):
        result += abs(count1[i] - count2[i])
    return result

makeAnagram('ab', 'bcdwed')

makeAnagram('gfrregewrf', 'fsasagrg')

makeAnagram('ab', 'bc')

