# -*- coding: utf-8 -*-
"""Copy of Competetive Coding I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nHw2LKYqt6dpSVdj7uOIx6yuwp1rTLWz

# Time : 1 hour

# Problem Statement

### A student is taking a cryptography class and has found anagrams to be very useful. Two strings are anagrams of each other if the first string's letters can be rearranged to form the second string. In other words, both strings must contain the same exact letters in the same exact frequency. For example, bacdc and dcbac are anagrams, but bacdc and dcbad are not.

### The student decides on an encryption scheme that involves two large strings. The encryption is dependent on the minimum number of character deletions required to make the two strings anagrams. You need to determine this number.

### Given two strings, $a$ and $b$, that may or may not be of the same length, determine the minimum number of character deletions required to make $a$ and $b$ anagrams. Any characters can be deleted from either of the strings. The strings $a$ and $b$ consist of lowercase English alphabets.

**Example**

<code>a = 'cde'</code>

<code>b = 'dcf' </code>

### Delete $e$ from $a$ and $f$ from $b$ so that the remaining strings are $cd$ and $dc$ which are anagrams. This takes 2 character deletions.

## **Function Description**

### Create a <code>makeAnagram</code> function below.

### **Inputs:**

### string a: a string

### string b: another string

### **Output:**

### int: the minimum total characters that must be deleted

# Solution
"""

# class makeAnagram():
#   def __init__(self,a,b):
#     count_fora=0
#     self.a=a.replace(" ","")
#     self.b=b.replace(" ","")
#     if(len(self.a)!=len(self.b)):
#       for var in self.a:
#         if var in self.b:
#           var_cnta=(self.a).count(var)
#           var_cntb=(self.b).count(var)
#           if(var_cnta == var_cntb):
#             pass
#           else:
#             if(var_cnta>var_cntb):
#               diffa=var_cnta-var.cntb
#               self.a.replace("var","",diffa)
#               count_fora=count_fora+1
#             elif(var_cnta<var_cntb):
#               diffb=var_cntb-var_cnta
#               self.b.replace("var","",diffb)
#               count_fora=count_fora+1
#     elif(len(self.a)==len(self.b)):
#           for var in self.a:
#             if var in self.b:
#               var_cnta=(self.a).count(var)
#               var_cntb=(self.b).count(var)
#               if(var_cnta == var_cntb):
#                 pass
#               else:
#                 if(var_cnta>var_cntb):
#                   diffa=var_cnta-var.cntb
#                   self.a.replace("var","",diffa)
#                   count_fora=count_fora+1
#                 elif(var_cnta<var_cntb):
#                   diffb=var_cntb-var.cnta
#                   self.b.replace("var","",diffb)
#                   count_fora=count_fora+1
#     print(count_fora)

class makeAnagram():
  def __init__(self,str1, str2):
    self.str1=str1
    self.str2=str2
    res=0
    n=26
    str1_blank=[0]*27
    str2_blank=[0]*27
    dict_alpnum={'a':0,'b':1,'c':2,'d':3,'e':4,'f':5,'g':6,'h':7,'i':8,'j':9,'k':10,'l':11,'m':12,'n':13,'o':14,'p':15,'q':16,'r':17,'s':18,'t':19,'u':20,'v':21,'w':22,'x':23,'y':24,'z':2,' ':26}
    for char in str1:
      char_index=dict_alpnum[char]
      str1_blank[char_index]=str1_blank[char_index]+1
    for char in str2:
      char_index2=dict_alpnum[char]
      str2_blank[char_index2]=str2_blank[char_index2]+1

    for i in range(27):
      diff=abs(str1_blank[i]-str2_blank[i])
      res=res+diff
    print(res)

anag=makeAnagram('a string','another string')



